server:
  port: 8081

logging:
  level:
    root: info
    org.springframework: debug
    org.springframework.security: debug
    org.springframework.oauth2: debug

spring:
  application:
    name: pharma-cash-management-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pharma-cash-keycloak

      client:
        registration:
          keycloak:
            provider: pharma-cash-keycloak
            client-id: pharma-cash-keycloak-client-service
            client-secret: "**********"
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
        provider:
          pharma-cash-keycloak:
            issuer-uri: http://localhost:8080/realms/pharma-cash-keycloak

keycloak:
  admin-api:
    auth-server-url: http://localhost:8080
    realm: pharma-cash-keycloak
    client-id: pharma-cash-admin-client
    client-secret: "mO8AbwQHlSOEaKBfVduoJ6OlH5JW1dfcXQJavHYQXjMhXfmEhuspPdKu20wKleehWSu7QMycX9wZINU4Ko8WxW"
  user:
    defaultPassword: "password"