server:
  port: 8081

logging:
  level:
    root: debug
    org.springframework: debug
    org.springframework.security: debug
    org.springframework.oauth2: debug

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pharmacash
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false

  flyway:
    locations: classpath:db/migration/postgres
    baseline-on-migrate: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/pharma-cash-keycloak

      client:
        registration:
          keycloak:
            provider: pharma-cash-keycloak
            client-id: pharma-cash-keycloak-client-service
            client-secret: "**********"
        provider:
          pharma-cash-keycloak:
            issuer-uri: http://localhost:8080/realms/pharma-cash-keycloak
